new_com

diff --git a/.github/workflows/conf.yml b/.github/workflows/conf.yml
--- a/.github/workflows/conf.yml
+++ b/.github/workflows/conf.yml
@@ -1,27 +1,41 @@
 name: Build
+
 on:
   push:
     branches:
       - main
   pull_request:
     types: [opened, synchronize, reopened]
+
 jobs:
   sonarcloud:
     name: SonarCloud
     runs-on: ubuntu-latest
+
     steps:
       - uses: actions/checkout@v3
         with:
           fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
+
+      - name: Install Java
+        uses: actions/setup-java@v2
+        with:
+          distribution: 'adopt'
+          java-version: '11'
+
       - name: Install SonarScanner
         run: |
           curl -sS https://downloads.sonarsource.com/sonar-scanner-cli/sonar-scanner-cli-4.7.1.4186-linux.zip -o sonar-scanner-cli-4.7.1.4186-linux.zip
-          unzip sonar-scanner-cli-4.7.1.4186-linux.zip
+          unzip -o -q sonar-scanner-cli-4.7.1.4186-linux.zip || echo "Failed to extract the SonarScanner CLI archive"
           sudo mv sonar-scanner-4.7.1.4186-linux /opt/sonar-scanner
           sudo ln -s /opt/sonar-scanner/bin/sonar-scanner /usr/local/bin/sonar-scanner
           sudo ln -s /opt/sonar-scanner/bin/sonar-scanner-debug /usr/local/bin/sonar-scanner-debug
           echo 'export PATH=$PATH:/opt/sonar-scanner/bin' >> ~/.bashrc
         shell: bash
+
+      - name: Check SonarScanner version
+        run: sonar-scanner --version
+
       - name: SonarCloud Scan
         uses: SonarSource/sonarcloud-github-action@master
         env:
